apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.tcp }}
      targetPort: tcp
      protocol: TCP
      name: tcp
    - port: {{ .Values.service.http }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.service.wss }}
      targetPort: wss
      protocol: TCP
      name: wss
  selector:
    {{- include "geth.selectorLabels" . | nindent 4 }}
