kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: geth-sc
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  fsType: ext4
  type: gp2
reclaimPolicy: Retain
allowVolumeExpansion: true