apiVersion: v2
name: geth
description: A Helm chart for Ethereum Go client
type: application
version: 0.1.0
icon: https://vulcanlink.github.io/charts/assets/img/ethereum.svg
keywords:
  - ethereum

home: https://ethereum.org/
sources:
  - https://github.com/ethereum/go-ethereum
maintainers:
  - name: Leo Vigna
    email: leo@vulcan.link

appVersion: latest
