apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: index-node
spec:
  selector:
    matchLabels:
      app: index-node
  serviceName: index-node
  replicas: 1
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: index-node
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8040"
    spec:
      nodeSelector:
        index: "1"
      tolerations:
        - key: "index"
          operator: "Exists"
          effect: "NoSchedule"
      volumes:
        - name: nfs-shared
          persistentVolumeClaim:
            claimName: nfs-shared
            readOnly: false
      containers:
        - name: graph-node
          image: graph-node-image
          resources:
            requests:
              cpu: 600m
          ports:
            - name: http
              containerPort: 8000
            - name: json-rpc
              containerPort: 8020
            - name: metrics
              containerPort: 8040
          volumeMounts:
            - name: nfs-shared
              mountPath: /var/lib/graph
          env:
            - name: node_id
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          envFrom:
            - configMapRef:
                name: {{ include "graphprotocol-indexer.fullname" . }}-configmap