apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parity-volume-claim
spec:
  storageClassName: parity-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage }}